Set distiluse model 4 good
etalab-ia/piaf-ml pull request #149
Opened 2021-07-27 10:41 UTC by psorianom

## Reference to a related issue

Fixes https://github.com/etalab-ia/piaf-ml/issues/85

## Why is the change needed

Long time ago, we were using sentence-transformers `distiluse` (dim-512) model without any hassle. One day, we decided to keep tabs on what version of the model we were using, for reproducibility sake. At the time, haystack did not have the option to use a specific version of a `sentence-transformers` model, so we changed to a transformers retriever with the `distilbert` (dim-768) model, because `distiluse` was not available in HF model's hub.

We were having a mix of `distiluse`, `distilbert` and a little bit of a mess with the dimensions in our code.

Also, the performance was not as good as with `distiluse`. Also, the model was finally uploaded to HF model's hub, so it is easily instantiate as a transformers model. This time the model has (dim-768) though :shrug:. 

## Description of the change

I removed all the sentence-transformers `distiluse` references and replaced them with the transformers' `sentence-transformers/distiluse-base-multilingual-cased-v2` identifier. All configurations mentioning `512` as number of dimensions where changed to `768`.

2021-07-27 12:38 UTC, Rob192 requested changes
We also need to update the client pipelines.yaml files to reflect this change

2021-07-27 12:38 UTC, Rob192 commented on test/test_eval_retriever.py
> +                             # ("sbert", 1, (5 * 1 / 2 + 11) / 16)]),
shall we remove the comment ?

2021-07-27 12:38 UTC, Rob192 commented on test/test_eval_retriever.py
> +                             ("sbert", 1., (3 * 1 / 2 + 13) / 16),
Looks better

2021-07-27 12:38 UTC, guillaumecherel approved these changes

2021-07-27 14:22 UTC, psorianom commented on test/test_eval_retriever.py
> +                             # ("sbert", 1, (5 * 1 / 2 + 11) / 16)]),
yep!

2021-07-27 14:47 UTC, psorianom commented
> We also need to update the client pipelines.yaml files to reflect this change

ah yes, I forgot those. Will do.

2021-07-27 17:20 UTC, guillim commented
Question : should we update this **"dims"** value as well to **728** ? Not sure if it's overridden later in the application
https://github.com/etalab-ia/piaf-ml/blob/8c71d614353a34a0762c2da6cc1080de8f2c5cc2/deployment/roles/prepare_data/templates/insert_data.py#L94

2021-07-27 17:26 UTC, psorianom commented
> Question : should we update this **"dims"** value as well to **728** ? Not sure if it's overridden later in the application
> 
> https://github.com/etalab-ia/piaf-ml/blob/8c71d614353a34a0762c2da6cc1080de8f2c5cc2/deployment/roles/prepare_data/templates/insert_data.py#L94

Nope, you're right, we should only have 768. Nothing uses 512 dimensions any more, for now.

2021-07-29 14:09 UTC, Rob192 approved these changes

2021-07-29 14:20 UTC, merged